### ISSUE TITLE
Missing some info about specifying the AppName and Token?

### ISSUE THREAD

**Issue by Maltazar** [MattMckenzy/Mail2Gotify#3]
Hi

This looks like what im missing, but im very much in doubt of how to setup the applications name and token that I did generate in the gotify admin interface?
Could you provide a bit more information?

Thanks for your time :)

**Comment by Maltazar** [comment]
Lol sorry I got it :)

**Comment by MattMckenzy** [comment]
Haha not a problem!
If you get stuck or have any issues, feel free to reach out again!

**Comment by Maltazar** [comment]
it was a bit to simple :P - main problem was that it have been all to long since I did setup an smtp connection :P - thanks for this nice app - working smooth on my local kubernetes cluster :D
