### ISSUE TITLE
does not load pfx cert?

### ISSUE THREAD

**Issue by Maltazar** [MattMckenzy/Mail2Gotify#4]
Hi Again.

I'm doing something wrong with loading the pfx file.
my appsettings.json looks like this:

{
  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "Services": {
    "Mail2Gotify": {
      "HostAddress": "localhost",
      "HostPort": 587,
      "CacheDirectory": "/app/cache",
      "CertLocation": "/app/Mail2Gotify.pfx"
    },
    "Gotify": {
      "ServiceUri": "http://gotify",
      "Header": "X-Gotify-Key"
    }
  },
  "Certificate": {
    "Name": "Mail2Gotify",
    "Password": "**********"
  }
}

I have tried with different format, with and without password - but it does not look like it loads it at all?
When I validate the certificate, its the autogenerated selfsigned cert - mine is also a selfsigned, but trusted in my infrastructure itself, and with my own auth.

any suggestions?

**Comment by MattMckenzy** [comment]
I just pushed an update that adds a bit more configuration options, could you check the README and see if the added explanation helps?

If not, do you get any log errors you could send to point me in the right direction?

**Comment by Maltazar** [comment]
You are fantastic! 
It works now, I have only testet with PEM format, but that is even better than pfx - because of automatic secrets with my k8s ExternalSecrets integration with Bitwarden :) Fantastic. I look forward to play with this a lot this weekend.
Have a great weekend when you get there

**Comment by MattMckenzy** [comment]
Glad I could help make it work for you!
