### ISSUE TITLE
Could not find the cache directory 

### ISSUE THREAD

**Issue by Compukid** [MattMckenzy/Mail2Gotify#6]
I tried to start the container, but received some errors.
mail2gotify  | Unhandled exception. System.Collections.Generic.KeyNotFoundException: Could not find the cache directory configuration at "Services:Mail2Gotify:CacheDirectory"

[compose] 
![mail2gotify_compose](https://github.com/MattMckenzy/Mail2Gotify/assets/7535046/31f0080e-dc21-4ad4-b488-ca7bbdc431d5)

[Error]
![mail2gotify_error](https://github.com/MattMckenzy/Mail2Gotify/assets/7535046/80ecb2b1-d716-4952-b74e-e88eabb87a1b)

[Docker log]
[error.log](https://github.com/MattMckenzy/Mail2Gotify/files/14620474/error.log)

[FYI]
The environment settings are in the env file, I hope that is ok?

**Comment by MattMckenzy** [comment]
The env file should be fine, but it seems like the variable: "Services:Mail2Gotify:CacheDirectory" isn't defined in it. It should be set to "/cache" in your case. Maybe double check to make sure your env file is valid and passed in properly!

**Comment by Compukid** [comment]
as a work around I removing the env_file and put back environment and it is up, but how do I configure pfsense for notifications???

specifically the Notification E-Mail address 
this is a requirement for pfsense. 

Once I can get pfsense to send a test message I will play around with the env_file again as that is my idle setup.

**Comment by MattMckenzy** [comment]
I've got it configured like this:
![image](https://github.com/MattMckenzy/Mail2Gotify/assets/7850521/027ac7f0-04c1-4246-b8b8-3e0c91f1700c)

The email is up to you, the important part for authentication is the username and password. The username should be the appname-notificationlevel (pfSense-6), and the password should be the app token you can retrieve in Gotify.

**Comment by Compukid** [comment]
<duh>
I forgot login, i knew I was missing something. That works, I played around with the env again and that still doesn't work. I am sure it is configured correctly, I'm not sure why it isn't working. with that said, where can I send you a cup of coffee or what ever you drink???

**Comment by MattMckenzy** [comment]
> I forgot login, i knew I was missing something. That works, I played around with the env again and that still doesn't work. I am sure it is configured correctly, I'm not sure why it isn't working. with that said, where can I send you a cup of coffee or what ever you drink???

Haha don't worry about it, I'm glad to help whenever I can!
